services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - python_app
      - grafana
    networks:
      - backend

  python_app:
    build: ./python
    container_name: python_app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:8.15.5
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - backend

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - backend

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: root
    entrypoint: telegraf
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOSTNAME=telegraf
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  influxdb_data:
  grafana_data:
